image:
  file: .gitpod.Dockerfile

ports:
  - port: 443
    onOpen: ignore
  - port: 80
    onOpen: open-browser

tasks:
  - init: |
      sudo adduser --disabled-password --gecos "" vpnuser
      echo "vpnuser:vpnpass123" | sudo chpasswd
    command: |
      sudo service ssh status
