image:
  file: .gitpod.Dockerfile

ports:
  - port: 22
    onOpen: ignore

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y openssh-server
      sudo service ssh start
    command: |
      sudo service ssh status
